name: outfits
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgets_book:
    path: packages/widgets_book

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
  fonts:
    - family: Urbanist
      fonts:
        - asset: packages/widgets_book/assets/fonts/Urbanist-Regular.ttf
        - weight: 400
        - asset: packages/widgets_book/assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: packages/widgets_book/assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: packages/widgets_book/assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: packages/widgets_book/assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: packages/widgets_book/assets/fonts/Urbanist-Black.ttf
          weight: 900
  uses-material-design: true