arb-dir: assets/l10n
template-arb-file: de.arb
output-localization-file: app_localizations.dart
#untranslated-messages-file: untranslated-messages.txt
synthetic-package: false
output-dir: lib/src/localization/l10n/gen